[workspace]

members = [
    "_01_stack_heap",
    "_02_concepts",
    "_03_grammar_concepts",
    "_03_grammar_scrape_url",
    "_04_httpie",
    "_05_thumbor",
    "_07_ownership",
    "_08_borrow"
]

#exclude = [
#    "_03_grammar"
#]
