[package]
name = "too_many_web_servers"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "simple"
path = "src/simple.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
